name: Test
on:
  push:
  workflow_dispatch:
concurrency:
  group: test
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          nix build -L -f default.nix nbdkit

  test-bsd:
    runs-on: ubuntu-latest
    steps:
      - uses: cross-platform-actions/action@v0.23.0
        with:
          operating_system: freebsd
          version: '14.0'
          shell: bash
          run: |
            sudo pkg install -y nix
            nix --experimental-features nix-command build -I nixpkgs=https://github.com/rhelmot/nixpkgs/archive/freebsd-minimal.tar.gz -L -f default.nix nbdkit
